name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_and_release.yml'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install needed stuff
        run: |
          sudo apt install fontconfig build-essential -y 
      - name: Build
        run: CC=/usr/bin/gcc CXX=/usr/bin/g++ cargo build --release
      - name: Bundle License and Executable
        run: |
          mkdir -p bundled
          cp LICENSE target/release/frigatify bundled/
      - name: Zip Release Artifact
        run: |
          zip linux_x86_64-unknown-linux-musl.zip frigatify LICENSE
        working-directory: bundled

      - name: Upload release artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: release
          path: bundled/linux_x86_64-unknown-linux-musl.zip
