name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_and_release.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install needed stuff
        run: apt install fontconfig build-essential
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Bundle License and Executable
        run: |
          mkdir -p bundled
          cp LICENSE target/release/frigatify bundled/
      - name: Zip Release Artifact
        run: |
          cd bundled
          zip linux_x86_64-unknown-linux-musl.zip frigatify LICENSE
        working-directory: bundled

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: bundled/linux_x86_64-unknown-linux-musl.zip
