name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build_and_release.yml'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install needed stuff
        run: |
          sudo apt install fontconfig build-essential -y 
      - name: Build
        run: CC=/usr/bin/gcc CXX=/usr/bin/g++ cargo build --release
      - name: Bundle License and Executable
        run: |
          mkdir -p bundled
          cp LICENSE target/release/frigatify bundled/
      - name: Zip Release Artifact
        run: |
          zip linux_x86_64.zip frigatify LICENSE
        working-directory: bundled

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@r0
        with:
          tag: latest
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: bundled/linux_x86_64.zip
