# .github/workflows/build_and_release.yml
name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch: {}
  push:
    paths:
        - '.github/workflows/build_and_release.yml'
        - 'src/*'
        - 'src/notify/*'
permissions: write-all
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
